const HANDOFF_KEY='publitex_quote_handoff_v1'; const SELECTION_KEY='publitex_quote_selection_v1';
const money=(n)=>new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(n);
function options(select,items,text){select.replaceChildren(); const blank=select.ownerDocument.createElement('option'); blank.value=''; blank.textContent=text; select.append(blank);items.forEach(x=>{const option=select.ownerDocument.createElement('option');option.value=x.id;option.textContent=x.label;select.append(option)});select.disabled=!items.length;}
export function initSimulator(documentRoot=document,api=fetch,storage=sessionStorage,navigate=(url)=>location.href=url){
 const root=documentRoot.querySelector('[data-simulator]'); if(!root)return {ready:Promise.resolve()};
 const category=root.querySelector('[data-simulator-category]'),product=root.querySelector('[data-simulator-product]'),quantity=root.querySelector('[data-simulator-quantity]'),price=root.querySelector('[data-simulator-price]'),status=root.querySelector('[data-simulator-status]'),estimate=root.querySelector('[data-simulator-estimate]'),result=root.querySelector('[data-simulator-result]'),summary=root.querySelector('[data-estimate-summary]'),total=root.querySelector('[data-estimate-total]'),quote=root.querySelector('[data-quote-project]'),observation=root.querySelector('[data-simulator-observation]'); let categories=[],selected;
 const show=(x)=>status.textContent=x;
 category.onchange=()=>{const c=categories.find(x=>x.id===category.value);options(product,c?.offerings||[],'Selecciona un servicio');quantity.disabled=true;price.textContent='';result.hidden=true;};
 product.onchange=()=>{selected=categories.flatMap(x=>x.offerings).find(x=>x.id===product.value);if(!selected)return;quantity.disabled=false;quantity.step=selected.unit==='UN'?'1':'0.01';quantity.value='';price.textContent=`${money(selected.unitPrice)} por ${selected.unit}`;result.hidden=true;};
 estimate.onclick=async()=>{if(!selected||!quantity.value)return show('Selecciona un servicio e ingresa una cantidad.'); const r=await api('/api/catalog/estimate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({offeringId:selected.id,quantity:quantity.value})});const b=await r.json();if(!r.ok)return show(b.error);summary.textContent=`${selected.label} · ${b.selection.quantity} ${selected.unit} · ${money(selected.unitPrice)} por ${selected.unit}`;total.textContent=money(b.estimatedTotal);result.hidden=false;quote.hidden=false;show('Estimación calculada.');};
 quote.onclick=()=>{storage.setItem(root.hasAttribute('data-quotation')?HANDOFF_KEY:SELECTION_KEY,JSON.stringify({offeringId:selected.id,quantity:Number(quantity.value),observation:observation.value.trim()}));navigate(root.hasAttribute('data-quotation')?'cotizaciones.html':'cotizacion.html');};
 const ready=(async()=>{const r=await api('/api/catalog');const b=await r.json();categories=b.categories||[];options(category,categories,'Selecciona una categoría');show('Servicios cargados.');})(); return {ready};
}
export {HANDOFF_KEY};
