CREATE TABLE catalog_categories (id TEXT PRIMARY KEY, label TEXT NOT NULL, sort_order INTEGER NOT NULL UNIQUE, active INTEGER NOT NULL DEFAULT 1 CHECK(active IN(0,1)));
CREATE TABLE catalog_offerings (id TEXT PRIMARY KEY, category_id TEXT NOT NULL REFERENCES catalog_categories(id), label TEXT NOT NULL, unit TEXT NOT NULL CHECK(unit IN('M2','ML','UN')), unit_price INTEGER NOT NULL CHECK(unit_price >= 0), sort_order INTEGER NOT NULL, active INTEGER NOT NULL DEFAULT 1 CHECK(active IN(0,1)), UNIQUE(category_id, sort_order));
INSERT INTO catalog_categories VALUES ('impresiones','Impresiones',1,1),('pintura','Pintura de fachada',2,1),('bastidores','Bastidores',3,1),('letreros','Letreros luminosos',4,1),('toldos','Toldos',5,1),('vinilos','Vinilo para ventanas',6,1),('otros','Otros',7,1);
INSERT INTO catalog_offerings (id,category_id,label,unit,unit_price,sort_order) VALUES
('tela-pvc-impresa','impresiones','Tela PVC impresa (tinta UV), solo impresión','M2',10500,1),('adhesivo-pvc-impreso','impresiones','Adhesivo PVC impreso (tinta UV), solo impresión','M2',14500,2),('tela-pvc-ojetillos','impresiones','Tela PVC impresa (tinta UV) sellada con ojetillos','M2',14500,3),('cenefa-personalizada','impresiones','Confección cenefa personalizada con logos C.COLA y logo cliente (ojetillada)','ML',4900,4),
('solo-pintura','pintura','Solo pintura','M2',8500,1),('pintura-raspado','pintura','Pintura con raspado','M2',10500,2),('pintura-interior','pintura','Solo pintura interior locales comerciales','M2',10500,3),('pintura-interior-retiro','pintura','Pintura interior con raspado o retiro de adhesivo','M2',10500,4),('pintura-logotipos','pintura','Pintura de logotipos (mínimo 1 MT2)','M2',35000,5),
('cambio-tela','bastidores','Solo cambio de tela','M2',18000,1),('bastidor-tela-fierro','bastidores','Bastidor con gráfica en tela PVC, fierro 20x20','M2',29500,2),('bastidor-20','bastidores','Bastidor en perfil 20x20, zinc 0,4 y gráfica adhesiva','M2',47000,3),('bastidor-30','bastidores','Bastidor en perfil 30x30, zinc 0,4 y gráfica adhesiva','M2',49500,4),
('letrero-1-faz','letreros','Letrero 1 faz','M2',135000,1),('letrero-doble-faz','letreros','Letrero doble faz','M2',135000,2),('mantencion-1-faz','letreros','Mantención letrero luminoso 1 faz','M2',38000,3),('mantencion-doble-faz','letreros','Mantención letrero luminoso doble faz','M2',45000,4),('cambio-tela-1-faz','letreros','Cambio de tela luminoso 1 faz','M2',27000,5),('cambio-tela-doble-faz','letreros','Cambio tela a letrero luminoso doble faz','M2',45000,6),('poste-metalico','letreros','Poste metálico 75 x 75, 6 mts.','UN',125000,7),('foco-led-30','letreros','Focos LED hasta 30 watts','UN',55000,8),('foco-led-150','letreros','Focos LED 100 - 150 watts','UN',137500,9),
('toldo-20','toldos','Confección estructura toldo fierro 20x20 tela SIL 001','M2',25000,1),('toldo-25','toldos','Confección estructura toldo fierro 25x25 tela SIL 002','M2',29500,2),('toldo-30','toldos','Confección estructura toldo fierro 30x30 tela SIL 002','M2',37000,3),('toldo-40','toldos','Confección estructura toldo fierro 40x30 tela SIL 002','M2',58500,4),('instalacion-toldo','toldos','Instalación toldo','M2',2500,5),('mantencion-toldo','toldos','Mantención de toldo, tela y pintura','M2',28000,6),
('windows-vision','vinilos','Windows Vision','M2',18000,1),('empavonado','vinilos','Empavonado','M2',18500,2),('empavonado-impreso','vinilos','Empavonado impreso','M2',22000,3),('empavonado-troquelado','vinilos','Empavonado troquelado','M2',25000,4),('astas-banderas','vinilos','Confección astas de banderas 6 MT.','UN',26000,5),('retiro-grafica','vinilos','Retiro gráfica adhesiva','M2',4000,6),('placa-trovicel','vinilos','Placa Trovicel, con gráfica adhesiva','M2',36000,7),('grafica-cooler','vinilos','Gráfica adhesiva para cooler','UN',41000,8),
('pendon-rollers','otros','Pendón rollers 2,00 x 0,90 MT. No incluye diseños','UN',48000,1);
