const test = require('node:test');
const assert = require('node:assert/strict');
const { withTestDatabase } = require('./database-helper');
const { createSimulationService } = require('../server/superadmin/simulation-service');
const { createAuthService } = require('../server/auth/auth-service');
const { createSqliteUserRepository } = require('../server/users/sqlite-user-repository');
const { createSqliteSessionRepository } = require('../server/auth/sqlite-session-repository');
const { createUserService } = require('../server/users/user-service');
const { requireUser } = require('../server/auth/authorization');

test('simulación conserva identidad real, aísla sesiones y rechaza privilegios falsificados', async () => {
  await withTestDatabase(async ({database}) => {
    const users = createSqliteUserRepository({database});
    const sessions = createSqliteSessionRepository({database});
    let id = 0;
    const userService = createUserService({users, createId: () => `user-${++id}`, hashPassword: p => p, verifyPassword: (p,h) => p === h});
    const authService = createAuthService({users,sessions,userService});
    const admin = await userService.createPrivilegedUser({name:'Admin',email:'admin@example.com',password:'password',role:'superadmin'});
    const client = await authService.register({name:'Client',email:'client@example.com',password:'password'});
    const a = await authService.login({email:admin.email,password:'password'});
    const b = await authService.login({email:admin.email,password:'password'});
    const service = createSimulationService({database,authService});
    await assert.rejects(service.setRole(client.token,'jefe'), {status:403});
    await assert.rejects(service.setRole('missing','jefe'), {status:401});
    await assert.rejects(service.setRole(a.token,'superadmin'), {status:400});
    await assert.rejects(service.setRole(a.token,{role:'jefe',id:client.user.id}), {status:400});
    const simulated = await service.setRole(a.token,'cliente');
    assert.equal(simulated.realUser.id, admin.id);
    assert.equal(simulated.user.id, admin.id);
    assert.notEqual(simulated.user.id, client.user.id);
    assert.equal(simulated.user.email, admin.email);
    assert.equal(simulated.simulation.ownerId,admin.id);
    assert.equal((await authService.getSessionUser(a.token)).role,'superadmin');
    assert.equal((await service.getContext(b.token)).simulation,null);
    assert.equal((await createSimulationService({database,authService}).getContext(a.token)).user.id,simulated.user.id);
    assert.equal(database.prepare('SELECT COUNT(*) AS n FROM simulation_users').get().n, 0);
    authService.getSessionContext = service.getContext;
    const request = {headers:{cookie:`publitex_session=${a.token}`}};
    await requireUser(authService)(request, {}, () => {});
    assert.equal(request.user.id,simulated.user.id);
    assert.equal(request.realUser.id,admin.id);
    assert.equal(request.simulation.ownerId,admin.id);
    await service.setRole(a.token,'jefe');
    assert.equal((await service.setRole(a.token,'cliente')).user.id,simulated.user.id);
    assert.equal((await service.setRole(a.token,null)).user.id,admin.id);
    await service.setRole(a.token,'trabajador');
    await authService.logout(a.token);
    assert.equal((await service.getContext(a.token)).user,null);
    assert.equal(database.prepare('SELECT count(*) AS n FROM session_simulations').get().n,0);
    await service.setRole(b.token,'jefe');
    database.prepare('UPDATE sessions SET expires_at = 0').run();
    await assert.rejects(service.setRole(b.token,null), {status:401});
    const events = database.prepare('SELECT * FROM simulation_events').all();
    assert.ok(events.some(e => e.action === 'exit'));
    assert.ok(events.every(e => e.actor_id === admin.id && e.created_at > 0));
  });
});

test('rutas exponen contexto superadmin y mantienen contrato ordinario de sesión', async () => {
  const { createAuthRouter } = require('../server/auth/auth-routes');
  const { createSimulationRouter } = require('../server/superadmin/simulation-routes');
  const response = () => ({statusCode:200,status(code){this.statusCode=code;return this;},json(body){this.body=body;return this;}});
  const invoke = async (router,path,method,request) => {
    const route = router.stack.find(layer => layer.route?.path === path && layer.route.methods[method]).route;
    const res = response();
    await route.stack[0].handle(request,res,error => {throw error;});
    return res;
  };
  let context = {user:{id:'demo',role:'cliente'},realUser:{id:'admin',role:'superadmin'},simulation:{role:'cliente',ownerId:'admin'}};
  const auth = createAuthRouter({authService:{getSessionContext:async () => context}});
  let res = await invoke(auth,'/session','get',{headers:{}});
  assert.equal(res.body.realUser.id,'admin');
  assert.equal(res.body.user.id,'demo');
  context = {user:{id:'ordinary',role:'cliente'},realUser:{id:'ordinary',role:'cliente'},simulation:null};
  res = await invoke(auth,'/session','get',{headers:{}});
  assert.deepEqual(res.body,{authenticated:true,user:context.user});
  let received;
  const router = createSimulationRouter({simulationService:{getContext:async () => context,setRole:async (...args) => {received=args;return context;}}});
  res = await invoke(router,'/','get',{headers:{}});
  assert.equal(res.statusCode,403);
  await invoke(router,'/role','post',{headers:{cookie:'publitex_session=actual'},body:{role:'jefe',token:'forged',userId:'forged'}});
  assert.deepEqual(received,['actual','jefe']);
});
